server:
  port: 8082

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_platform
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

account-service:
  base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,mappings,env
  endpoint:
    health:
      show-details: always